--video 135: Duration: 05:28 Difference between sequence and identity in sql server


--| Identity |
---> Identity property is a table column property meaning it is tied to the table
---> To generate the next identity value, a row has to be insetred into the table
---> Maximum value for the identity property cannot be specified. The maximum value will be the maximum value of the correspoding column data type.
---> Identity property does not have any option to automatically restart the identity values

--| Sequence |
 ---> Sequence is a user-defined database object and is not tied to any specific table meaning it's value can be shared by multiple tables.
 ---> With sequence object there is no need to insert a row into the table to generate the next sequence value. You can use NEXT VALUE FOR clause to generate the next sequence value.
 ---> With the sequence object you can use the MAXVALUE option to specify the maximum value. If the MAXVALUE option is not specified for the sequence object, then the maximum value will be the maximum value of it's data type.
 ---> With the Sequence object CYCLE option can be used to specify whether the sequence should restart automatically when the max value (for incrementing sequence object) or min value (for decrementing sequence object) is reached.


 CREATE TABLE tbl135Customers
(
    Id INT PRIMARY KEY,
    Name NVARCHAR(50),
    Gender NVARCHAR(10)
)
GO

CREATE TABLE tbl135Users
(
    Id INT PRIMARY KEY,
    Name NVARCHAR(50),
    Gender NVARCHAR(10)
)
GO

CREATE SEQUENCE [dbo].[SequenceObject]
AS INT
START WITH 1
INCREMENT BY 1


INSERT INTO tbl135Customers VALUES (NEXT VALUE FOR [dbo].[SequenceObject], 'Ben', 'Male')
INSERT INTO tbl135Customers VALUES (NEXT VALUE FOR [dbo].[SequenceObject], 'Sara', 'Female')

INSERT INTO tbl135Users VALUES (NEXT VALUE FOR [dbo].[SequenceObject], 'Tom', 'Male')
INSERT INTO tbl135Users VALUES (NEXT VALUE FOR [dbo].[SequenceObject], 'Pam', 'Female')
INSERT INTO tbl135Users VALUES (NEXT VALUE FOR [dbo].[SequenceObject], 'David', 'Male')
GO

SELECT * FROM tbl135Customers
SELECT * FROM tbl135Users

select NEXT VALUE FOR [dbo].[SequenceObject]

INSERT INTO tbl135Users VALUES (NEXT VALUE FOR [dbo].[SequenceObject], 'David-after generated by select', 'Male')


DROP SEQUENCE [dbo].[SequenceObject]

CREATE SEQUENCE [dbo].[SequenceObject]
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 5
CYCLE

SELECT NEXT VALUE FOR [dbo].[SequenceObject]